name: Netlify Document Staging Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publishMasterCommit:
    name: Deploying on Netlify Document Staging Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.action == 'closed' && github.event.pull_request.merged == 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: docs/document
      - name: Replace kucLink
        run: sed -i 's|https://unpkg.com/kintone-ui-component/umd/kuc.min.js|/js/kuc.min.js|' docusaurus.config.js
        working-directory: docs/document
      - name: Install dependencies on root
        run: npm ci
      - name: Build umd file
        run: npm run build:umd_prod
      - name: Move umd file
        run: mv umd/kuc.min.js docs/document/static/js
      - name: Build document
        run: npm run build
        working-directory: docs/document
      - name: Install Netlify
        run: npm i netlify-cli --no-save
      - name: Deploy
        run: netlify deploy --dir=./docs/document/build --alias=staging --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_DOCUMENT_ID }}
